# Chapter 7: Array Oriented Programming with NumPy
## Jarrod Sims
### 7.2 Creating arrays from Existing Data

In [14]:
print('Jarrod Sims')

Jarrod Sims


In [2]:
import numpy as np

In [3]:
numbers = np.array([2, 3, 5, 7, 11])

In [4]:
type(numbers)

numpy.ndarray

In [5]:
numbers

array([ 2,  3,  5,  7, 11])

In [6]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
np.array([[2, 4, 6, 8, 10] , [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

### 7.3 Array Attributes

In [15]:
print('Jarrod Sims')

Jarrod Sims


In [10]:
import numpy as np
integers = np.array([[1, 2, 3], [4, 5, 6]])
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [12]:
integers.dtype

dtype('int32')

In [13]:
floats.dtype

dtype('float64')

In [16]:
integers.ndim

2

In [17]:
floats.ndim

1

In [18]:
integers.shape

(2, 3)

In [19]:
floats.shape

(5,)

In [20]:
integers.size

6

In [21]:
integers.itemsize

4

In [22]:
floats.size

5

In [23]:
floats.itemsize

8

In [24]:
print('Jarrod Sims')

Jarrod Sims


In [36]:
for row in integers:
    for column in row:
        print(column, end='  ')
    print()

1  2  3  
4  5  6  


In [35]:
for i in integers.flat:
    print(i, end=' ')

1 2 3 4 5 6 

In [38]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim)
print(a.shape)

2
(2, 3)


### 7.4 Filling arrays with Specific Values

In [39]:
print('Jarrod Sims')

Jarrod Sims


In [41]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.ones((2, 4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
np.full ((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

### 7.5 Creating arrays from Ranges

In [45]:
print('Jarrod Sims')

Jarrod Sims


In [48]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [49]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [50]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [51]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [56]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [57]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [59]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [60]:
np.arange(2, 41, 2).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

### 7.6 List vs. array Performance: Introducing %timeit

In [62]:
print('Jarrod Sims')

Jarrod Sims


In [1]:
import random
%timeit rolls_list = \
   [random.randrange(1, 7) for i in range(0, 6_000_000)]

4.3 s ± 110 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
import numpy as np
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

52.5 ms ± 607 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%timeit rolls_array = np.random.randint(1, 7, 60_000_000)

513 ms ± 5.37 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%timeit rolls_array = np.random.randint(1, 7, 600_000_000)

5.05 s ± 13.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

53.9 ms ± 1.78 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [8]:
%timeit sum([x for x in range(10_000_000)])

801 ms ± 2.92 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
%timeit np.arange(10_000_000).sum()

14.5 ms ± 108 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### 7.7 array Operators

In [11]:
print('Jarrod Sims')

Jarrod Sims


In [12]:
import numpy as np
numbers = np.arange(1, 6)
numbers

array([1, 2, 3, 4, 5])

In [13]:
numbers * 2 

array([ 2,  4,  6,  8, 10])

In [14]:
numbers ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [15]:
numbers 

array([1, 2, 3, 4, 5])

In [16]:
numbers += 10
numbers

array([11, 12, 13, 14, 15])

In [18]:
numbers2 = np.linspace(1.1, 5.5, 5)
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [20]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [21]:
numbers

array([11, 12, 13, 14, 15])

In [22]:
numbers >= 13

array([False, False,  True,  True,  True])

In [23]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [24]:
numbers2 > numbers

array([False, False, False, False, False])

In [25]:
numbers == numbers2

array([False, False, False, False, False])

In [26]:
np.arange(1, 6) ** 2

array([ 1,  4,  9, 16, 25])

### 7.8 NumPy Calculation Methods

In [36]:
print('Jarrod Sims')

Jarrod Sims


In [29]:
grades = np.array ([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [30]:
grades.sum()

1054

In [31]:
grades.min()

70

In [32]:
grades.max()

100

In [33]:
grades.mean()

87.83333333333333

In [34]:
grades.std()

8.792357792739987

In [35]:
grades.var()

77.30555555555556

In [37]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [38]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [42]:
grades = np.random.randint(60, 101, 12).reshape(3, 4)
grades

array([[89, 86, 83, 62],
       [83, 68, 74, 81],
       [61, 75, 61, 69]])

In [43]:
grades.mean()

74.33333333333333

In [44]:
grades.mean(axis=0)

array([77.66666667, 76.33333333, 72.66666667, 70.66666667])

In [45]:
grades.mean(axis=1)

array([80. , 76.5, 66.5])

### 7.9 Universal Functions

In [46]:
print('Jarrod Sims')

Jarrod Sims


In [57]:
numbers = np.array([1, 4, 9, 16, 25, 36])
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [58]:
numbers2 = np.arange(1, 7) * 10
numbers2

array([10, 20, 30, 40, 50, 60])

In [59]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

In [60]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [61]:
numbers3 = numbers.reshape(2, 3)
numbers3

array([[ 1,  4,  9],
       [16, 25, 36]])

In [62]:
numbers4 = np.array([2, 4, 6])
np.multiply(numbers3, numbers4)

array([[  2,  16,  54],
       [ 32, 100, 216]])

In [63]:
numbers = np.arange(1,6)
np.power(numbers, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

### 7.10 Indexing and Slicing

In [64]:
print('Jarrod Sims')

Jarrod Sims


In [65]:
grades = np.array ([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [66]:
grades[0, 1]

96

In [67]:
grades[1]

array([100,  87,  90])

In [68]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [69]:
grades[[1,3]]

array([[100,  87,  90],
       [100,  81,  82]])

In [70]:
grades [:, 0]

array([ 87, 100,  94, 100])

In [72]:
grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

In [74]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [75]:
a[1]

array([ 6,  7,  8,  9, 10])

In [76]:
a[[1,2]]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [77]:
a[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

### Views: Shallow Copies

In [78]:
print('Jarrod Sims')

Jarrod Sims


In [80]:
numbers = np.arange(1, 6)
numbers

array([1, 2, 3, 4, 5])

In [83]:
numbers2 = numbers.view()
numbers2

array([1, 2, 3, 4, 5])

In [84]:
id(numbers)

1875324554672

In [85]:
id(numbers2)

1875614760560

In [87]:
numbers[1] *= 10
numbers2

array([  1, 200,   3,   4,   5])

In [88]:
numbers

array([  1, 200,   3,   4,   5])

In [90]:
numbers2[1] /= 10
numbers

array([1, 2, 3, 4, 5])

In [91]:
numbers2

array([1, 2, 3, 4, 5])

In [92]:
numbers2 = numbers[0:3]
numbers2

array([1, 2, 3])

In [93]:
id(numbers)

1875324554672

In [95]:
id(numbers2)

1875324528272

In [96]:
numbers2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [99]:
numbers = np.arange(1, 6)
numbers[1] *= 20
numbers

array([ 1, 40,  3,  4,  5])

In [100]:
numbers2

array([ 1, 40,  3])

### 7.12 Deep Copies

In [101]:
print('Jarrod Sims')

Jarrod Sims


In [103]:
numbers = np.arange(1, 6)
numbers

array([1, 2, 3, 4, 5])

In [105]:
numbers2 = numbers.copy()
numbers2

array([1, 2, 3, 4, 5])

In [107]:
numbers[1] *= 10
numbers

array([  1, 200,   3,   4,   5])

In [108]:
numbers2

array([1, 2, 3, 4, 5])

### Reshaping and Transposing

In [116]:
print('Jarrod Sims')

Jarrod Sims


In [109]:
grades = np.array([[87, 96, 70], [100, 87, 90]])
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [110]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [111]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [112]:
grades = np.array([[87, 96, 70], [100, 87, 90]])
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [114]:
flattend = grades.flatten()
flattend

array([ 87,  96,  70, 100,  87,  90])

In [115]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [120]:
flattend[0] = 100
flattend

array([100,  96,  70, 100,  87,  90])

In [121]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [123]:
raveled = grades.ravel()
raveled

array([ 87,  96,  70, 100,  87,  90])

In [124]:
raveled[0] = 100
raveled

array([100,  96,  70, 100,  87,  90])

In [125]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [126]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [127]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [128]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

In [129]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [132]:
a = np.arange(1, 7).reshape(2, 3)
a = np.hstack((a, a))
a = np.vstack((a, a))
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])